### PR TITLE
Sort out angular implementation of map service

### LINKED ISSUE #80: Feedback on update room button
When editing a room in the game using the web UI if you click the update button there is no feedback to say that the changes have been saved.

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #80

Signed-off-by: Erin Schnabel <schnabel@us.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-webapp/84)

### CODE REVIEW

**Comment by MarkNSweep** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/public/scripts/controllers/site.js, line 23 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4_41ZhukL4eSzMDIm:-KV4_41ZhukL4eSzMDIn:b-u3r8ic) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/controllers/site.js#L23)):*
> ```JavaScript
> 
>     this.createRoom = function() {
>       $log.debug("createRoom %o", siteCtrl.roomConfig, siteCtrl.activeSite);
> ```

Need another %o

---

*[src/public/scripts/controllers/site.js, line 47 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4_ypc8tH6wjEwUOVm:-KV4_ypc8tH6wjEwUOVn:bm5fddl) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/controllers/site.js#L47)):*
> ```JavaScript
>           $log.debug('deleteRoom OK %o', response);
>           delete siteCtrl.activeSite;
>           // TODO: remove element with matching id
> ```

Presumably this is now done as calling getSites() which will replace the list of rooms entirely

---

*[src/public/scripts/services/map.js, line 27 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4dW8NvxAarDKUNcgd:-KV4dW8NvxAarDKUNcge:b-at6lfr) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/services/map.js#L27)):*
> ```JavaScript
>       url: mapurl,
>       method: 'GET',
> //      params: {owner: gid},
> ```

Going to get back all rooms without the owner parameter

---

*[src/public/scripts/services/map.js, line 62 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4fTe38pk-GNPzDWoD:-KV4fTe38pk-GNPzDWoE:bxd15k6) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/services/map.js#L62)):*
> ```JavaScript
>         // 201: room created
>         $log.debug(response.status + ' ' + response.statusText + " OK %o", response.data);
>         q.resolve(response.data);
> ```

Should we actually check this is 201 and if not q.reject() it ? (same question for the other OK handlers in this service)

---

*[src/public/templates/play.myrooms.html, line 107 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4lbolyUHvqZ5wCKuD:-KV4lbolyUHvqZ5wCKuE:b-1ny2zo) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/templates/play.myrooms.html#L107)):*
> ```HTML
>                 placeholder="ws://<hostname:portnumber>/<context-root>"/>
>           </div>
>           <div class="two columns">
> ```

Do we have more testing to do coming up, or can we take this out now ?

---

*[test/services/map.test.js, line 21 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4m3t1qJymQfqIgqZc:-KV4m3t1qJymQfqIgqZd:buruoom) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/test/services/map.test.js#L21)):*
> ```JavaScript
>     });
> 
>     it('is benign on empty', function() {
> ```

Is this a duplicate test ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84)*

**Comment by ebullient** [comment]
Reviewed 2 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/public/scripts/controllers/site.js, line 23 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4_41ZhukL4eSzMDIm:-KV5I_emeeCEB2ZYGCo_:b2nign3) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/controllers/site.js#L23)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary>
> Need another %o
</details>
yep

---

*[src/public/scripts/controllers/site.js, line 47 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4_ypc8tH6wjEwUOVm:-KV5HkJZE3Y3m0GfOvYv:b-4tdwl0) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/controllers/site.js#L47)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary>
> Presumably this is now done as calling getSites() which will replace the list of rooms entirely
</details>
No. this clears the field that populates the form. Replacing the list just changes the content of the dropdown. You need both.

---

*[src/public/scripts/services/map.js, line 27 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4dW8NvxAarDKUNcgd:-KV5Hrjq1AQYZwBgUVxu:bzjyns) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/services/map.js#L27)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary>
> Going to get back all rooms without the owner parameter
</details>
Yep. this needs to go back pre-push.

---

*[src/public/scripts/services/map.js, line 62 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4fTe38pk-GNPzDWoD:-KV5Hvs4N9pSHWgs5sl2:b-5ozxdq) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/scripts/services/map.js#L62)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary>
> Should we actually check this is 201 and if not q.reject() it ? (same question for the other OK handlers in this service)
</details>
201 is ok. I don't think I would want to reject a 200, though w/  API definition, nothing else will be returned.

---

*[src/public/templates/play.myrooms.html, line 107 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4lbolyUHvqZ5wCKuD:-KV5I7_J4f52Xq0-Qi2g:b-o7lf1e) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/src/public/templates/play.myrooms.html#L107)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary>
> Do we have more testing to do coming up, or can we take this out now ?
</details>
This is the place holder for the button you want to add later, that will allow people to press a button to test the connection to their room. I assume we'll have a follow on, I am laying the groundwork for where that goes.

---

*[test/services/map.test.js, line 21 at r1](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KV4m3t1qJymQfqIgqZc:-KV5IL6enSIEiEbCO3ok:b-7wbhqn) ([raw file](https://github.com/gameontext/gameon-webapp/blob/650a82e3e97332803458402ffdc612675832a896/test/services/map.test.js#L21)):*
<details><summary><i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary>
> Is this a duplicate test ?
</details>
Maybe. Not finished with this test thing at all: I have no idea what I'm doing here, need help from @klhamilton

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84)*

**Comment by ebullient** [comment]
Reviewed 2 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84)*

**Comment by ebullient** [comment]
Reviewed 2 of 11 files at r1, 8 of 10 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/public/styles/gameon.css, line 26 at r2](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84#-KVBQ5Vsuy3aPzBVAGUJ:-KVBQ5Vsuy3aPzBVAGUK:bmqix1u) ([raw file](https://github.com/gameontext/gameon-webapp/blob/a61c11422b4017c0a6d4c04e339aeff5da6afa6e/src/public/styles/gameon.css#L26)):*
> ```CSS
>   background-repeat: no-repeat;
> }
> ```

These changes make top/bottom smaller with narrow windows / phones

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84)*

**Comment by MarkNSweep** [comment]
Reviewed 8 of 10 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-webapp/84)*

**Pull request merged**
